language: racket

sudo: required

env:
 - RACKET_VERSION=6.1

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

script:
  - make install && make test
