language: racket

sudo: required

env:
 - RACKET_VERSION=6.1

before_install:
- git clone https://github.com/dpiccone/travis-racket.git
- cat travis-racket/install-racket.sh | bash

install:

before_script:

script:
    - /usr/racket/bin/raco test --direct --table unit/

after_script:
